name: Cloud Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set Up Docker
        run: |
          sudo apt update
          sudo apt install docker.io -y

      - name: Build & Push Docker Image
        run: |
          docker build -t security-backend .
          docker tag security-backend:latest <AWS_CONTAINER_REGISTRY>/security-backend:latest
          docker push <AWS_CONTAINER_REGISTRY>/security-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Container on AWS EC2
        run: |
          ssh -i ${{ secrets.AWS_SSH_KEY }} ubuntu@${{ secrets.AWS_EC2_IP }} "docker pull <AWS_CONTAINER_REGISTRY>/security-backend:latest && docker run -d -p 5000:5000 security-backend"
